name: Local Supabase
values:
  - key: baseUrl
    value: 'http://127.0.0.1:54321/functions/v1'
  - key: userId
    value: 00000000-0000-0000-0000-000000000001
  - key: date
    value: '2026-03-02'
  - key: recordId
    value: ''
color: 120
